# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=18)),
                ('location', models.CharField(max_length=100)),
                ('basically_intact_square', models.CharField(max_length=6)),
                ('damaged_square', models.CharField(max_length=6)),
                ('destroyed_square', models.CharField(max_length=6)),
                ('note', models.CharField(max_length=200)),
                ('reporting_unit', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'CivilStructure',
            },
        ),
        migrations.CreateModel(
            name='CollapseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=18)),
                ('location', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=10)),
                ('status', models.CharField(default='', max_length=10)),
                ('picture', models.ImageField(default='', upload_to='')),
                ('note', models.TextField(default='', max_length=200)),
                ('reporting_unit', models.TextField(default='202', max_length=50)),
            ],
            options={
                'db_table': 'CollapseRecord',
            },
        ),
        migrations.CreateModel(
            name='CommDissaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=18)),
                ('location', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=4)),
                ('grade', models.CharField(default='', max_length=4)),
                ('picture', models.ImageField(default='', upload_to='')),
                ('note', models.TextField(default='', max_length=200)),
                ('reporting_unit', models.TextField(default='202', max_length=50)),
            ],
            options={
                'db_table': 'CommDissaster',
            },
        ),
        migrations.CreateModel(
            name='DeathStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=18)),
                ('number', models.IntegerField()),
                ('reporting_unit', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'DeathStatistics',
            },
        ),
        migrations.CreateModel(
            name='DisasterPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=18)),
                ('location', models.CharField(default='', max_length=100)),
                ('longitude', models.FloatField(default='', max_length=100)),
                ('latitude', models.FloatField(default='', max_length=100)),
                ('depth', models.FloatField(default='')),
                ('magnitude', models.FloatField(default='')),
                ('intensity', models.CharField(default='', max_length=6)),
                ('type', models.CharField(default='', max_length=2)),
                ('picture', models.ImageField(default='', upload_to='')),
                ('note', models.TextField(default='', max_length=200)),
                ('reporting_unit', models.TextField(default='', max_length=50)),
            ],
            options={
                'db_table': 'DisasterPrediction',
            },
        ),
        migrations.CreateModel(
            name='DisasterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=18)),
                ('disasterType', models.CharField(default='', max_length=3)),
                ('status', models.CharField(default='', max_length=1)),
                ('o_URL', models.CharField(default='', max_length=200)),
                ('requesting', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'DisasterRequest',
            },
        ),
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('ID', models.CharField(default='', max_length=19, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=4)),
                ('detail', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'TotalData',
            },
        ),
        migrations.AddField(
            model_name='disasterrequest',
            name='ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receiveData.TotalData'),
        ),
        migrations.AddField(
            model_name='disasterprediction',
            name='ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receiveData.TotalData'),
        ),
        migrations.AddField(
            model_name='deathstatistics',
            name='ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receiveData.TotalData'),
        ),
        migrations.AddField(
            model_name='commdissaster',
            name='ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receiveData.TotalData'),
        ),
        migrations.AddField(
            model_name='collapserecord',
            name='ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receiveData.TotalData'),
        ),
        migrations.AddField(
            model_name='civilstructure',
            name='ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receiveData.TotalData'),
        ),
    ]
