# Generated by Django 3.0.5 on 2020-05-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiveData', '0002_auto_20200525_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasterrequest',
            name='ID',
        ),
    ]
